# Dev environment configuration for Influencer Platform backend infrastructure
config:
  # Google Cloud Settings
  gcp:project: project-35d3eed2-c73d-4ab5-998
  gcp:region: europe-west1
  # Resource Names
  influencer-platform:storage_bucket_name: your-influencer-platform-images-bucket
  influencer-platform:artifact_registry_repo_name: influencer-platform-repo
  # Cloud Run Performance Tuning (Optional, defaults will be used if omitted)
  influencer-platform:cloud_run_service_name: influencer-platform-backend
  influencer-platform:cloud_run_max_instances: "5"
  influencer-platform:cloud_run_memory: 512Mi
  influencer-platform:cloud_run_cpu: "1"
  influencer-platform:cloud_run_image: europe-west1-docker.pkg.dev/project-35d3eed2-c73d-4ab5-998/influencer-platform-repo/influencer-platform-backend:latest
  influencer-platform:instagram_cookies:
    secure: AAABACndbzXkWO6YRubsOx6OUtL8bZhlV/NAJU6z+qEalIaCiaq67msMaSBAEfybhE0CFwq1OZRfUInk7qlf6yYmq+OfNEOagAA0jroa5KfkQkLhHZ33/51SD4bsrKAB8H5GndCoH6Bt9ifMvOKmJKzeuCj52RXKDZ2oBtJA9u12+9gQZcKVNJGi2RH6gmrSODLc1XYWEmRAh8w8jG4IjAJpJMezBLbnvcQawxYnEhJTkGmhU6YA/OPeI2PtERDftPhKJo+rtFr5F/QC552f4qPuaINLEEhH3FrVRahT9tOhtqqcZZeJSySr3eBFaRlPKXWT4GHreGTk0kQwX/HuzKvHH+mJ4q4WXR3/eB45oNKCzjlRKGFG4oETwC7+QExKjOm+9iDAu/7jtf1hGPRKhLILUcJExA27VRKg7q5REHF9a2zI26Fvvk7vKkZMRgG71TfjR/h5K5/Glk1D53IBMu+vsYUaz8I5jUZ2UlCJDJecLSJCjDrr6jGoHVmeXmmBggZj438AY6KtvH9kIG/ZFoj/cao41QxaPLLAONkdK1M0zXdW0cVPl9ALzM/SmapmBmTo4HYvvle/DQksE2/2NwoA2SMKJeKgX6bCx/eJP9XI3VrAesfhYDei71cRyrRTeBP1In8dD4qEIWBGFrqYZPgschTiDtt78BL8otVgrITUT4U7/Rbk8OlfS/q5KuuvPUc8EfP5bo8fhS5KHSxxeOjyw/PJDSBU61/KcxSJ04nOhPZ7wLVMXFJehWCBcc68c4i4FqASE2daE04xdqdnLv3J0Ai2SMXaQcBoRUxjD7O5HRK66pgT4sGjfdUYr7uJ+bAHlU+dO3/OjWOsFj5f5n9ly/Yjf7vsi99c+1T688e0qOow37hUL2v+8a/NEoHz1ZG88nBACdxe9juONpqENt7B0qEVfvpIXn1xljXZyYobX/xxpVXsbXxk/x+aI+uReqnTqlYU4eBb3pv2jTlPCE4z7OP1shUgG+vOVTUGaEumPuunQ/f+
  influencer-platform:telegram_bot_webhook_url: https://influencer-platform-backend-q6oetpmpfa-ew.a.run.app/api/v1/telegram-webhook
  influencer-platform:telegram_bot_token:
    secure: AAABAMIUwpzgVnuIos1dV+iR9TNJMyfepNXcYJ5YvPMhyHSU6Ig45C7Eym3utVoP8jzfbVuonLN4kAS861ReYppToVPlUWD6BAR8N8mb
