# Dev environment configuration for Influencer Platform backend infrastructure
config:
  # Google Cloud Settings
  gcp:project: project-35d3eed2-c73d-4ab5-998
  gcp:region: europe-west1
  # Resource Names
  influencer-platform:storage_bucket_name: your-influencer-platform-images-bucket
  influencer-platform:artifact_registry_repo_name: influencer-platform-repo
  # Cloud Run Performance Tuning (Optional, defaults will be used if omitted)
  influencer-platform:cloud_run_service_name: influencer-platform-backend
  influencer-platform:cloud_run_max_instances: "5"
  influencer-platform:cloud_run_memory: 512Mi
  influencer-platform:cloud_run_cpu: "1"
  influencer-platform:cloud_run_image: europe-west1-docker.pkg.dev/project-35d3eed2-c73d-4ab5-998/influencer-platform-repo/influencer-platform-backend@sha256:72b7f97c04523e387055acc8e1cb84613abb22fa946579f3e1d4ed16d7943dee
  influencer-platform:instagram_cookies:
    secure: AAABAJhiUnCS/A15dRzr6+6WpygZN/87vHbDza74rX/Nw5K3qND3hfCwCumaZFEEMnXf2p9R+dJc006lf6liYaE2kNklhGPSV3FP7O98uczn6Sj6QzLjt1MIk4JCJamTxD5SONX+RgVdBfNUBvh7hrtMzrYchQutgnkpYZBXPDDJ5hNLsjFyvLrjjfatvohmwmQU/Qsvwfj0dAvpyq2ptcT+evKKGgJDcWe7Pxm0wwbTEV7c1X3zo7mvYvVC7+ap0jnS8eF1aDpElNuo0DDW8r8ngc+BgRwL7Ddw+cVeJFCUiROZ5MRUMjVvwZHaqnLP4sR8V2S4GLPEHJnqvatJ4kI38Y8XQfxHExvldXqQdrW7Ib4sA6VZ0j44ItSJUHgHPvg6gma3WqmKpDPkPI9iLjBrLMzKC+yq/4gGTU8QVkROKw6jUgX/DBoTFORyh/ypZ4u1QsmOa5mcqFoTLzFMr8iXATQeckBVj3S4s8AnHcOGbt0b6wqrsosaJuFp8EPSjmoL+f+wsOAdzYxeoT9q8lrHOpeSlpEcs1vxZ6gkG19yk0n5p/OZIPIV4Jls132HlyYCfb279tL6NzDTBObFYt4fU8gVbvTYzz35U5a+NwEALVqMaznUNH7ckAFA25VjK/es54EAU2oC2SE7mHMN6XClkiNGgyGhiTJxisGhRa/HpSnSzBH2+aXgHHxU3FCtIjHIll7BAf+idbfSZYhZoTL/fnSh4/X4isuc5vSqLrdAsrGWhuFWUuWd+ZxVl9jFrHsNA+t4LsLufGPfbXwwHWVnQsJEtwAbIRoVE2TwgipgaE4/Ol/6z4Pt0ZxbJ4bF3Pl7xiw51kaFAdUmKxrZMIoMgP8tFqXt/be/3gBWkGHbcLmXL383l0UN9t59Gm/wrIQ2xkfezvcfV25roHQ8Kj194OzAAoWUZ0R8OYPdbGLISZMUBUH2Nv+48b3VZYGBsxye5QoLqfDxap6GDgsqQppH/klDitcyByR4Mnqhy46Gwj05
